name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
    runs-on: ubuntu-latest
    
    steps:

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 16
        # Used to pull node distributions from node-versions.  Since there's a default, this is typically not supplied by the user.
        token: ${{ secrets.ACCESS_TOKEN }}
      - run: yarn
      - run: yarn run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      env:
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build
        BUILD_SCRIPT: npm install && npm run build